---
title: "Lecture 1.3"
date: 2024-01-08
editor-options:
  
---

```{r}
library(tidyverse)
library(ggplot2)
library(palmerpenguins)
```

## Tidy Data
```{r}
# untidy data ----
temp_data_wide <- tribble(
  ~date, ~station1, ~station2,  ~station3,
  "2023-10-01", 30.1, 29.8,  31.2,
  "2023-11-01", 28.6, 29.1,  33.4,
  "2023-12-01", 29.9, 28.5,  32.3
)

# make tidy ----
temp_data_long <- temp_data_wide |> 
  pivot_longer(cols = starts_with("station"),
               names_to = "station_id", 
               values_to = "temp_c")
```


```{r}
# look at the structure of the data frame using st()
# str(penguins)
# map our aesthetics using aes
ggplot(data = na.omit(penguins), aes(x = bill_length_mm,
                                    y = bill_depth_mm,
                                    color = species)) +
  geom_point()

# --- piping your data ---
ggplot() +
  geom_point(data = penguins, 
             mapping = aes(x = bill_lenght_mm,
                           y = bill_depth_mm))

# --- line of best fit within each species ---
ggplot(penguins, aes(x = bill_length_mm, y = bill_depth_mm, color = species)) +
  geom_point() +
  geom_smooth(method = "lm")

# --- line of best fith through all species ---
ggplot(data = na.omit(penguins), aes(x = bill_length_mm,
                                    y = bill_depth_mm)) +
  geom_point(aes(color = species)) +
  geom_smooth(method = "lm")


# --- now to change the color scale ----
ggplot(penguins, aes(x = body_mass_g,
                     y = flipper_length_mm,
                     color = body_mass_g)) +
  geom_point() +
  scale_color_gradient(low = "#132B43", high = "#f7DD4C")

```
## Plot 2 
```{r}

# ---underlying geom statistic is "identity"
ggplot(penguins, aes(x = species)) +
  geom_bar()
```

**Overriding geom_bar's stat:**

```{r}
penguins_summary <- penguins %>% 
  count(species)

ggplot(penguins_summary, aes(x = species, y = n)) +
  geom_bar(stat = "identity")
```

**Position Adjustments:**
```{r}
# default position is "stack"
ggplot(penguins, aes(x = species, fill = island )) +
  geom_bar(position  = "dodge")
  # geom_bar(position = "fill")

```

**coordinate systems**
```{r}
ggplot(penguins, aes( x = species)) +
  geom_bar() +
  coord_flip() + # swithced the axis
  theme_classic() + # lots of themes
  theme(
    axis.title = element_text(size = 17, color = "purple")
  )
```



